# Generated by Django 5.1.2 on 2024-10-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pomen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя кого-то')),
                ('pomen', models.CharField(max_length=100, verbose_name='Поменял кого-то')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Помен',
                'verbose_name_plural': 'Помени',
            },
        ),
    ]
